import torch
import random

def clamp_int8(x):
    return max(-128, min(127, x))

def main():
    torch.manual_seed(0)
    random.seed(0)

    N = 4
    K = 4

    # Random int8-ish values
    A = torch.randint(low=-8, high=8, size=(N, K), dtype=torch.int32)
    B = torch.randint(low=-8, high=8, size=(K, N), dtype=torch.int32)
    C = A @ B

    # Create systolic "edge streams" for K cycles:
    # Each cycle provides a column of A? or row? depends on your array feeding convention.
    #
    # For your current design, you’ve been feeding:
    # - a0..a3 = A column elements at time t (down the rows)
    # - b0..b3 = B row elements at time t (across the cols)
    #
    # So we stream:
    # cycle t: a = [A0t, A1t, A2t, A3t]
    #          b = [Bt0, Bt1, Bt2, Bt3]
    #
    # This matches a standard 2D systolic injection for NxN GEMM.
    lines = []
    lines.append("# stream_vectors.txt generated by PyTorch\n")
    lines.append("# Format:\n")
    lines.append("# A a0 a1 a2 a3   (K lines)\n")
    lines.append("# B b0 b1 b2 b3   (K lines)\n")
    lines.append("# C c00..c33 row-major (16 lines)\n\n")

    for t in range(K):
        a_vec = [int(A[r, t].item()) for r in range(N)]
        lines.append(f"A {a_vec[0]} {a_vec[1]} {a_vec[2]} {a_vec[3]}\n")

    for t in range(K):
        b_vec = [int(B[t, c].item()) for c in range(N)]
        lines.append(f"B {b_vec[0]} {b_vec[1]} {b_vec[2]} {b_vec[3]}\n")

    # row-major dump of C
    for r in range(N):
        for c in range(N):
            lines.append(f"C {int(C[r, c].item())}\n")

    with open("stream_vectors.txt", "w") as f:
        f.writelines(lines)

    print("A=\n", A)
    print("B=\n", B)
    print("C=\n", C)
    print("\nWrote stream_vectors.txt")

if __name__ == "__main__":
    main()
