// tb/tb_sa4x4_pytorch.sv 
// Reads vectors.txt generated by py/gen_vectors.py
`timescale 1ns/1ps

module tb_sa4x4_pytorch;

  localparam int N = 4;
  localparam int ACC_W = 32;
  localparam int T = 12;

  logic clk, reset, en;

  logic signed [7:0] a0, a1, a2, a3;
  logic signed [7:0] b0, b1, b2, b3;

  logic signed [ACC_W-1:0] c00, c01, c02, c03;
  logic signed [ACC_W-1:0] c10, c11, c12, c13;
  logic signed [ACC_W-1:0] c20, c21, c22, c23;
  logic signed [ACC_W-1:0] c30, c31, c32, c33;

  sa4x4 #(.ACC_W(ACC_W)) dut (
    .clk(clk), .reset(reset), .en(en),
    .a0(a0), .a1(a1), .a2(a2), .a3(a3),
    .b0(b0), .b1(b1), .b2(b2), .b3(b3),
    .c00(c00), .c01(c01), .c02(c02), .c03(c03),
    .c10(c10), .c11(c11), .c12(c12), .c13(c13),
    .c20(c20), .c21(c21), .c22(c22), .c23(c23),
    .c30(c30), .c31(c31), .c32(c32), .c33(c33)
  );

  always #5 clk = ~clk;

  integer fd;
  reg [8*256-1:0] line;  

  integer A [0:N-1][0:N-1];
  integer B [0:N-1][0:N-1];
  integer C_ref [0:N-1][0:N-1];

  integer i, t;

  // temps for reading matrix rows
  integer x0, x1, x2, x3;

  // temps for reading inject lines
  integer tmp_a0, tmp_a1, tmp_a2, tmp_a3;
  integer tmp_b0, tmp_b1, tmp_b2, tmp_b3;

  // Seek marker lines 
  task automatic seek_marker(input [8*16-1:0] marker);
    integer found;
    reg [8*32-1:0] tok;
    begin
      found = 0;
      while (!$feof(fd) && !found) begin
        if ($fgets(line, fd)) begin
          tok = "";
          if ($sscanf(line, "%s", tok) == 1) begin
            if (tok == marker) found = 1;
          end
        end
      end
      if (!found) $fatal(1, "Marker %0s not found in vectors.txt", marker);
    end
  endtask

  task automatic check_outputs;
    begin
      if (c00 !== C_ref[0][0]) $fatal(1,"Mismatch C[0][0]: got %0d exp %0d", c00, C_ref[0][0]);
      if (c01 !== C_ref[0][1]) $fatal(1,"Mismatch C[0][1]: got %0d exp %0d", c01, C_ref[0][1]);
      if (c02 !== C_ref[0][2]) $fatal(1,"Mismatch C[0][2]: got %0d exp %0d", c02, C_ref[0][2]);
      if (c03 !== C_ref[0][3]) $fatal(1,"Mismatch C[0][3]: got %0d exp %0d", c03, C_ref[0][3]);

      if (c10 !== C_ref[1][0]) $fatal(1,"Mismatch C[1][0]: got %0d exp %0d", c10, C_ref[1][0]);
      if (c11 !== C_ref[1][1]) $fatal(1,"Mismatch C[1][1]: got %0d exp %0d", c11, C_ref[1][1]);
      if (c12 !== C_ref[1][2]) $fatal(1,"Mismatch C[1][2]: got %0d exp %0d", c12, C_ref[1][2]);
      if (c13 !== C_ref[1][3]) $fatal(1,"Mismatch C[1][3]: got %0d exp %0d", c13, C_ref[1][3]);

      if (c20 !== C_ref[2][0]) $fatal(1,"Mismatch C[2][0]: got %0d exp %0d", c20, C_ref[2][0]);
      if (c21 !== C_ref[2][1]) $fatal(1,"Mismatch C[2][1]: got %0d exp %0d", c21, C_ref[2][1]);
      if (c22 !== C_ref[2][2]) $fatal(1,"Mismatch C[2][2]: got %0d exp %0d", c22, C_ref[2][2]);
      if (c23 !== C_ref[2][3]) $fatal(1,"Mismatch C[2][3]: got %0d exp %0d", c23, C_ref[2][3]);

      if (c30 !== C_ref[3][0]) $fatal(1,"Mismatch C[3][0]: got %0d exp %0d", c30, C_ref[3][0]);
      if (c31 !== C_ref[3][1]) $fatal(1,"Mismatch C[3][1]: got %0d exp %0d", c31, C_ref[3][1]);
      if (c32 !== C_ref[3][2]) $fatal(1,"Mismatch C[3][2]: got %0d exp %0d", c32, C_ref[3][2]);
      if (c33 !== C_ref[3][3]) $fatal(1,"Mismatch C[3][3]: got %0d exp %0d", c33, C_ref[3][3]);
    end
  endtask

  initial begin
    $dumpfile("sim/sa4x4_pytorch.vcd");
    $dumpvars(0, tb_sa4x4_pytorch);

    clk = 0; reset = 1; en = 0;
    a0 = 0; a1 = 0; a2 = 0; a3 = 0;
    b0 = 0; b1 = 0; b2 = 0; b3 = 0;

    fd = $fopen("vectors.txt", "r");
    if (fd == 0) $fatal(1, "Could not open vectors.txt (run python script first)");

    // Read A
    seek_marker("A:");
    for (i = 0; i < N; i = i + 1) begin
      void'($fgets(line, fd));
      if ($sscanf(line, "%d %d %d %d", x0, x1, x2, x3) != 4)
        $fatal(1, "Bad A row line: %0s", line);
      A[i][0]=x0; A[i][1]=x1; A[i][2]=x2; A[i][3]=x3;
    end

    // Read B
    seek_marker("B:");
    for (i = 0; i < N; i = i + 1) begin
      void'($fgets(line, fd));
      if ($sscanf(line, "%d %d %d %d", x0, x1, x2, x3) != 4)
        $fatal(1, "Bad B row line: %0s", line);
      B[i][0]=x0; B[i][1]=x1; B[i][2]=x2; B[i][3]=x3;
    end

    // Read C_ref
    seek_marker("C:");
    for (i = 0; i < N; i = i + 1) begin
      void'($fgets(line, fd));
      if ($sscanf(line, "%d %d %d %d", x0, x1, x2, x3) != 4)
        $fatal(1, "Bad C row line: %0s", line);
      C_ref[i][0]=x0; C_ref[i][1]=x1; C_ref[i][2]=x2; C_ref[i][3]=x3;
    end

    // Read inject lines
    seek_marker("INJECT:");

    // Reset
    repeat (3) @(posedge clk);
    reset = 0;
    @(posedge clk);
    en = 1;

    for (t = 0; t < T; t = t + 1) begin
      void'($fgets(line, fd));
      if ($sscanf(line, "%d %d %d %d %d %d %d %d",
                  tmp_a0,tmp_a1,tmp_a2,tmp_a3,tmp_b0,tmp_b1,tmp_b2,tmp_b3) != 8)
        $fatal(1, "Bad INJECT line: %0s", line);

      a0 = tmp_a0; a1 = tmp_a1; a2 = tmp_a2; a3 = tmp_a3;
      b0 = tmp_b0; b1 = tmp_b1; b2 = tmp_b2; b3 = tmp_b3;

      @(posedge clk);
      #1;
    end

    // Flush
    repeat (3) @(posedge clk);
    en = 0;
    @(posedge clk);
    #1;

    check_outputs();
    $display("PASS: RTL sa4x4 matches PyTorch golden model.");
    $finish;
  end

endmodule
